name: Deploy to Shared Hosting

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Deploy to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: /test/
          dangerous-clean-slate: true
          exclude: |
            .env
            uploads/**
            node_modules/**
            package-lock.json
            package.json
            www/**
