name: Deploy to hosting server

on:
  push:
    branches:
      - deploy # Déploiement sur push dans la branche 'deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout source code
        uses: actions/checkout@v3

      # Étape 2 : Configurer le cache des modules Node.js
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm ci # Utilise npm ci pour garantir un environnement propre

      # Étape 4 : Construire le projet
      - name: Build project
        run: npm run build

      # Étape 5 : Configurer les algorithmes SSH (si nécessaires)
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "    KexAlgorithms +diffie-hellman-group-exchange-sha256" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
      # Étape 6 : Déployer via SFTP
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./dist/
          target: /test
          timeout: 120s
          debug: true
