name: Deploy to hosting server

on:
  push:
    branches:
      - deploy # Déploiement sur push dans la branche 'deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout source code
        uses: actions/checkout@v3

      # Étape 2 : Configurer le cache des modules Node.js
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Étape 3 : Installer les dépendances
      # - name: Install dependencies
      #   run: npm ci # Utilise npm ci pour garantir un environnement propre

      # # Étape 4 : Construire le projet
      # - name: Build project
      #   run: npm run build

      - name: Create .env file
        run: |
          cat > .env << 'EOF'
          NODE_ENV=production
          DATABASE_URL=localhost
          PORT=3000
          JWT_SECRET=coming
          EOF

      - name: Copy files to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H sshcloud.cluster024.hosting.ovh.net:42710 >> ~/.ssh/known_hosts
          rsync -avz ./ louiiuj@sshcloud.cluster024.hosting.ovh.net:42710:/home/louiiuj/test

      # Étape 5: Installer ssh pass
      # - name: Install sshpass
      #   run: sudo apt-get update && sudo apt-get install -y sshpass

      #   # Étape 5 : Tester la connexion SSH
      # - name: Test SSH connection
      #   env:
      #     SCP_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
      #   run: |
      #     sshpass -p "${SCP_PASSWORD}" ssh -P 42710 -o StrictHostKeyChecking=no louiiuj-lmc@sshcloud.cluster024.hosting.ovh.net "echo 'SSH connection successful'"

      # Étape 6 : Transférer le build vers le serveur OVH
      # - name: Upload build to OVH server
      #   env:
      #     SCP_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
      #   run: |
      #     sshpass -p "${SCP_PASSWORD}" scp -P 42710 -v -r ./dist/ louiiuj-lmc@sshcloud.cluster024.hosting.ovh.net:/home/louiiuj/test

      # # Étape 6 : Transférer le build vers le serveur OVH via SCP avec login/mot de passe
      - name: Upload build to OVH server
        env:
          SCP_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
        run: |
          sshpass -p "${SCP_PASSWORD}" scp -r ./dist/ louiiuj-lmc@sshcloud.cluster024.hosting.ovh.net

      # - name: Configure custom SSH port
      #   run: |
      #     echo "Host ${OVH_HOSTING_DOMAIN}" >> ~/.ssh/config
      #     echo "    Port 42710" >> ~/.ssh/config # Changez '42710' par le port fourni par OVH
      #     echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      # - name: Deploy to OVH hosting
      #   uses: pitscher/ovh-deploy-hosting-action@v1
      #   env:
      #     OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
      #     OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
      #     OVH_HOSTING_DOMAIN: ${{ secrets.OVH_HOSTING_CLUSTER }}
      #     REPOSITORY_NAME: lmc-api
      #     REPOSITORY_URL: https://github.com/louiiuol/lmc-api.git
